version: '3.7'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  cron-job:
    build:
      context: ./
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/mydatabase
    env_file:
      - .env
    depends_on:
      - postgres